version: '3.9'
services:
  backend:
    build: .
    container_name: course-api
    env_file:
      - .env.production
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15
    container_name: course-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2009
      POSTGRES_DB: online_courses_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
