services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - path: .
          target: /app
          action: sync
        - path: ./package.json
          target: /app/package.json
          action: rebuild
    container_name: course-api
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: course-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2009
      POSTGRES_DB: online_courses_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
